// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/health" | "/*";
  };
  "./routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "./routes/health.ts": {
    id: "routes/health";
    page: "/health";
  };
  "./routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/index": typeof import("./src/app/./routes/index.tsx");
  "routes/health": typeof import("./src/app/./routes/health.ts");
  "routes/not-found": typeof import("./src/app/./routes/not-found.tsx");
};